return {
    { "€", "euro" },
    { "ƒ", "latin small letter f with hook" },
    { "„", "double low-9 quotation mark" },
    { "…", "ellipsis" },
    { "†", "dagger" },
    { "‡", "double dagger" },
    { "ˆ", "modifier letter circumflex accent" },
    { "‰", "per mille" },
    { "š", "latin capital letter s with caron" },
    { "‹", "single left-pointing angle quotation" },
    { "œ", "latin capital ligature oe" },
    { "’", "right single quotation mark" },
    { "“", "left double quotation mark" },
    { "”", "right double quotation mark" },
    { "•", "bullet" },
    { "–", "en dash" },
    { "—", "em dash" },
    { "˜", "small tilde" },
    { "™", "trade mark" },
    { "š", "latin small letter s with caron" },
    { "›", "single right-pointing angle quotation mark" },
    { "œ", "latin small ligature oe" },
    { "ÿ", "latin capital letter y with diaeresis" },
    { "¡", "inverted exclamation mark" },
    { "¢", "cent" },
    { "£", "pound" },
    { "¤", "currency" },
    { "¥", "yen" },
    { "¦", "broken vertical bar" },
    { "§", "section" },
    { "¨", "spacing diaeresis" },
    { "©", "copyright" },
    { "ª", "feminine ordinal indicator" },
    { "«", "left double angle quotes" },
    { "¬", "negation" },
    { "®", "registered trade mark" },
    { "¯", "spacing macron" },
    { "°", "degree " },
    { "±", "plus or minus" },
    { "²", "superscript two" },
    { "³", "superscript three" },
    { "´", "acute accent" },
    { "µ", "micro " },
    { "¶", "paragraph" },
    { "·", "middle dot" },
    { "¸", "spacing cedilla" },
    { "¹", "superscript one" },
    { "º", "masculine ordinal indicator" },
    { "»", "right double angle quotes" },
    { "¼", "fraction one quarter" },
    { "½", "fraction one half" },
    { "¾", "fraction three quarters" },
    { "¿", "inverted question mark" },
    { "à", "latin capital letter a with grave" },
    { "á", "latin capital letter a with acute" },
    { "â", "latin capital letter a with circumflex" },
    { "ã", "latin capital letter a with tilde" },
    { "ä", "latin capital letter a with diaeresis" },
    { "å", "latin capital letter a with ring above" },
    { "æ", "latin capital letter ae" },
    { "ç", "latin capital letter c with cedilla" },
    { "è", "latin capital letter e with grave" },
    { "é", "latin capital letter e with acute" },
    { "ê", "latin capital letter e with circumflex" },
    { "ë", "latin capital letter e with diaeresis" },
    { "ì", "latin capital letter i with grave" },
    { "í", "latin capital letter i with acute" },
    { "î", "latin capital letter i with circumflex" },
    { "ï", "latin capital letter i with diaeresis" },
    { "ð", "latin capital letter eth" },
    { "ñ", "latin capital letter n with tilde" },
    { "ò", "latin capital letter o with grave" },
    { "ó", "latin capital letter o with acute" },
    { "ô", "latin capital letter o with circumflex" },
    { "õ", "latin capital letter o with tilde" },
    { "ö", "latin capital letter o with diaeresis" },
    { "×", "multiplication" },
    { "ø", "latin capital letter o with slash" },
    { "ù", "latin capital letter u with grave" },
    { "ú", "latin capital letter u with acute" },
    { "û", "latin capital letter u with circumflex" },
    { "ü", "latin capital letter u with diaeresis" },
    { "ý", "latin capital letter y with acute" },
    { "þ", "latin capital letter thorn" },
    { "ß", "latin small letter sharp s - ess-zed" },
    { "à", "latin small letter a with grave" },
    { "á", "latin small letter a with acute" },
    { "â", "latin small letter a with circumflex" },
    { "ã", "latin small letter a with tilde" },
    { "ä", "latin small letter a with diaeresis" },
    { "å", "latin small letter a with ring above" },
    { "æ", "latin small letter ae" },
    { "ç", "latin small letter c with cedilla" },
    { "è", "latin small letter e with grave" },
    { "é", "latin small letter e with acute" },
    { "ê", "latin small letter e with circumflex" },
    { "ë", "latin small letter e with diaeresis" },
    { "ì", "latin small letter i with grave" },
    { "í", "latin small letter i with acute" },
    { "î", "latin small letter i with circumflex" },
    { "ï", "latin small letter i with diaeresis" },
    { "ð", "latin small letter eth" },
    { "ñ", "latin small letter n with tilde" },
    { "ò", "latin small letter o with grave" },
    { "ó", "latin small letter o with acute" },
    { "ô", "latin small letter o with circumflex" },
    { "õ", "latin small letter o with tilde" },
    { "ö", "latin small letter o with diaeresis" },
    { "÷", "divided by" },
    { "ø", "latin small letter o with slash" },
    { "ù", "latin small letter u with grave" },
    { "ú", "latin small letter u with acute" },
    { "û", "latin small letter u with circumflex" },
    { "ü", "latin small letter u with diaeresis" },
    { "ý", "latin small letter y with acute" },
    { "þ", "latin small letter thorn" },
    { "ÿ", "latin small letter y with diaeresis" },
}
