return {
    { "!", "exclamation mark" },
    { "#", "hashtag" },
    { "$", "dollar" },
    { "%%", "percent" },
    { "%+", "plus" },
    { "&", "and" },
    { "'", "single quote" },
    { "%(", "open bracket" },
    { "%)", "close bracket" },
    { "*", "asterisk" },
    { ",", "comma" },
    { "%.", "dot" },
    { "/", "foreword divide" },
    { ":", "colon" },
    { ";", "semicolon" },
    { "<", "less than" },
    { "=", "equals" },
    { ">", "greater than" },
    { "?", "question mark" },
    { "@", "at" },
    { "%[", "open square bracket" },
    { "\\", "backslash" },
    { "%]", "close square bracket" },
    { "^", "caret" },
    { "^", "caret" },
    { "_", "underscore" },
    { "`", "grave accent" },
    { "{", "opening brace" },
    { "|", "bar" },
    { "}", "closing brace" },
    { "~", "tilde" },
    { [["]], "double quote" },
}
